sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product sitcomtn-001
env:
  global:
    - secure: "ij2rLd1/tvzjyddzgJsqCZCdb+310SdgbWGJ2SIFUcWUklkEZNpDaxa0K24nSeYJhWivUV8+cvZ+c1gUhYeH/Gg2PCkW9Ew4MCYgli/HO0Y3/jnWC7BO+Uy10ySVLxD5eH4xtTPqZHY+/eXhtzER4wg1i4ZGWpfndhOuovqd+gvxfkg5srRT69f0M/mgJSHH1dzzS9CBSZRtcT4rYveMIfAOGDNdXkQHHmx6fcfEynSsqMHwfT1mVROFpRVXrXinBdomaiA6hw0vzpI8vQa8Rohc3ChB13Xzi29JZP1qPjzAd5s+LuPDkgIzjet3jT3TgM/n4stRTIcj6CkkfhN30V5lE9+daCwhUoS+1VDUCMs5fOsc43UdXUAiNwzTfh0iXpcZ1WxucepNVllpLR3D1DEZ/cG2QOdUQGK3eqrJo9926VVtYMwkuvrIn9OMUWqLiP0gZsNea30LbxW/ogNZfPSjQWYotxPdRUSS9WMlBFq9bsjhsJwVeYuq3uSlvyVp29oq9GEOKZfWEwj2YjyuOJhlwOxW8+qHOLOG77unztjS6edveRiQ61PXh7aTFiQnUl3Q6oPamie3dGob3WU3vU7xLQUyfjv8vni7jG2xAFrYGwwhzHZyCYvTeQH71sPbZdHyu1MXHB9JUqGMmelRC/9zX4p299jufrW5hca0n74="
    - secure: "M24P2UZVjI+ECLYAaa6KmSnWsM8HOgYNhM7+ZWA68eSF1b6gSVzGezDPhR6nZk9vvX7buxwGfMQo9uJ8k8ogrqot2OmwLfxHST02yief93RJHjRNQIfE3mZJrXj+VJWyx827m3eTIaqBNd3/zdDFMWHARuqlagNoOe0RCZw3yhtvHgLpt+E4Katg8VQjDIXg6QuuftmKb8iiF/so8bu4j8vQm4U4EeKh7JVDdlQGCMI/vWeW0lB8wy5/rZR1syjF3pOfHONG6jhIGB7GMJl3/9RKIQKFXY2IE9PDz/bNMCuGbqyE0f7TrU2gcocaYlVEOoVfVVq7BwlCUVRU5M2aj8lgsZbl38KXKxEdS9E+1XI0IuX/KOaPCr7okbCHyvZTFHLZNco18v+EjDfnN5xUwRfNODKMryNG+k/pq35DhFdmCVphpUpK5I2g0IpVi4Nm7WDtPaIXpJgTwGBvYqJVBrVO2+4gS9STLmqo2d/E6TishdN1WqSWEW6hZAQQ+RO9YLiKmHp2W+TlvDEG2FaiLjNGcRfnhnjCWWZ+V3vm8/puN9gz/HhSvBTnHpfhmTcmmp5aOC3qV9MGdfnoeGw+LTmqPQn93LMBsZpyz4hESuxEpaAgeJuIyQcxiY7xX+6maTHbs1NJXjv8IRsJ3lDz+c9uHhTysq4tljBjJFkefiY="
